#!/bin/bash

# Colors for better output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

printf "%b" "${BLUE}🚀 Starting SIoTD Project Environment Setup...${NC}\n"

# Define variables
PROJECT_DIR="$HOME/Desktop/SIoTD-Projects"
VENV_DIR="$PROJECT_DIR/siotdenv"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to print section header
print_section() {
    local section_title="$1"
    local section_length=$(( ${#section_title} + 8 ))
    local separator=$(printf '─%.0s' $(seq 1 $section_length))
    printf "\n%b\n" "${BLUE}┌${separator}┐"
    printf "%b\n" "│   🚀 ${section_title}  │"
    printf "%b\n" "└${separator}┘${NC}"
}

# Function to print status
print_status() {
    if [ $? -eq 0 ]; then
        printf "%b\n" "${GREEN}✅ $1${NC}"
    else
        printf "%b\n" "${YELLOW}⚠️  $2${NC}"
        return 1
    fi
}

# Create project directory
print_section "Setting up project directory"
if [ -d "$PROJECT_DIR" ]; then
    printf "%b\n" "${YELLOW}ℹ️  Project directory already exists at $PROJECT_DIR${NC}"
else
    mkdir -p "$PROJECT_DIR"
    print_status "Created project directory at $PROJECT_DIR" "Failed to create project directory"
fi

# Create environment configuration file
ENV_CONFIG="$SCRIPT_DIR/siotd_env.conf"
print_section "Creating environment configuration"
cat > "$ENV_CONFIG" << EOL
# SIoTD Environment Configuration
# This file is automatically generated by siotd_env_setup.sh
# Do not edit this file manually as it will be overwritten

# Project Directories
PROJECT_DIR="$PROJECT_DIR"
VENV_DIR="$VENV_DIR"

# Application Directories
MOSQUITTO_DIR="\$PROJECT_DIR/mosquitto"
MOSQUITTO_CONFIG="\$MOSQUITTO_DIR/mosquitto.conf"
MOSQUITTO_DATA="\$MOSQUITTO_DIR/data"
MOSQUITTO_LOG="\$MOSQUITTO_DIR/log"

# InfluxDB Configuration
INFLUXDB_DIR="\$PROJECT_DIR/influxdb"

# Python Virtual Environment
VIRTUAL_ENV="\$VENV_DIR"

# Colors for output
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
RED='\\033[0;31m'
NC='\\033[0m' # No Color
EOL

# Make the environment file executable
chmod +x "$ENV_CONFIG"
print_status "Created environment configuration at $ENV_CONFIG" "Failed to create environment configuration"

# Navigate to project directory
cd "$PROJECT_DIR" || { printf "%b\n" "${RED}❌ Failed to navigate to $PROJECT_DIR${NC}" >&2; exit 1; }

# Check and install python3-venv if needed
print_section "Checking Python virtual environment package"
if ! dpkg -s python3-venv >/dev/null 2>&1; then
    printf "%b\n" "${BLUE}Installing python3-venv...${NC}"
    sudo apt-get update
    sudo apt-get install -y python3-venv
    print_status "Installed python3-venv" "Failed to install python3-venv"
else
    printf "%b\n" "${YELLOW}ℹ️  python3-venv is already installed${NC}"
fi

# Create virtual environment
print_section "Setting up Python virtual environment"
if [ -d "$VENV_DIR" ]; then
    printf "%b\n" "${YELLOW}ℹ️  Virtual environment already exists at $VENV_DIR${NC}"
else
    printf "%b\n" "${BLUE}Creating Python virtual environment...${NC}"
    python3 -m venv "$VENV_DIR" --system-site-packages
    print_status "Created virtual environment at $VENV_DIR" "Failed to create virtual environment"
fi

# Activate virtual environment
print_section "Activating virtual environment"
if [ -f "$VENV_DIR/bin/activate" ]; then
    printf "%b\n" "${BLUE}Activating virtual environment...${NC}"
    # Use . instead of source for better compatibility
    . "$VENV_DIR/bin/activate"
    if [ $? -eq 0 ] && [ -n "$VIRTUAL_ENV" ]; then
        printf "%b\n" "${GREEN}✅ Virtual environment activated${NC}"
    else
        printf "%b\n" "${YELLOW}⚠️  Virtual environment activation failed${NC}"
        exit 1
    fi
else
    printf "%b\n" "${RED}❌ Virtual environment activation script not found at $VENV_DIR/bin/activate${NC}"
    exit 1
fi

# Install required packages
print_section "Installing Python packages"
pip install --upgrade pip
pip install setuptools wheel
print_status "Updated pip and installed setuptools and wheel" "Failed to install Python packages"

# Final instructions
printf "\n%b\n" "${GREEN}🎉 Python environment setup completed successfully!${NC}"
